version: "3.8"
services:
  timesheet-app: 
    image: php:8.0-apache
    ports:
      - 80:80
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
  mysql:
    image: mariadb:latest
    volumes:
      - timesheet-mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: timesheet
  phpmyadmin:
    image: phpmyadmin:latest
    ports: 
      - 8080:80
    environment:
      PMA_HOST: mysql
  ldap_server:
    image: ldap-server:latest
    environment:
      LDAP_ADMIN_PASSWORD: test1234
      LDAP_BASE_DN: dc=testorg
    ports:
      - 389:389
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
  ldap_server_admin:
    image: ldap_server_admin:latest
    ports:
      - 8090:80
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap_server
      PHPLDAPADMIN_HTTPS: 'false'
volumes:
  ldap_data:
  ldap_config:
  timesheet-mysql-data:
